/** Brand-first portfolio data and case-study modal. */
const PROJECTS_URL = '/api.php?_query=projects';
let siteBrands = [], allPortfolioProjects = [], lastProjectTrigger = null;
function safeUrl(v){ const raw=String(v||'').trim(); if(!raw)return ''; if(raw.startsWith('/')||/^https?:\/\//i.test(raw)) return raw; return ''; }
function isVideo(v){return /\.(mp4|webm|mov|m4v|ogv|ogg|avi|mkv)(\?.*)?$/i.test(v||'') || /youtube|vimeo/i.test(v||'');}
async function loadProjects(){try {const r=await fetch(PROJECTS_URL,{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json(); allPortfolioProjects=(d.projects||[]).filter(p=>p.published!==false);siteBrands=(d.brands||[]).sort((a,b)=>(a.order||0)-(b.order||0)); return allPortfolioProjects;}catch(e){console.error(e);return [];}}
function mediaEl(url, title, controls=false){ const safe=safeUrl(url); if(!safe)return document.createElement('div'); if(isVideo(safe)&&!/youtube|vimeo/i.test(safe)){const v=document.createElement('video');v.src=safe;v.controls=controls;v.playsInline=true;v.preload='metadata';return v;}const i=document.createElement('img');i.src=safe;i.alt=title||'';i.loading='lazy';return i; }
function renderProjects(){const grid=document.getElementById('workGrid');if(!grid)return;grid.innerHTML=''; const brands=siteBrands.filter(b=>allPortfolioProjects.some(p=>String(p.brand)===String(b.id))); if(!brands.length){grid.innerHTML='<div class="projects-public-empty"><h3>No brands published yet</h3><p>New work will appear here soon.</p></div>';return;}brands.forEach(brand=>{const count=allPortfolioProjects.filter(p=>String(p.brand)===String(brand.id)).length, card=document.createElement('button');card.type='button';card.className='brand-card';card.setAttribute('aria-haspopup','dialog'); const img=mediaEl(brand.thumbnail,brand.name);img.className='brand-card-image';card.append(img);const overlay=document.createElement('span');overlay.className='brand-card-overlay';overlay.innerHTML='<strong></strong><small></small>';overlay.querySelector('strong').textContent=brand.name;overlay.querySelector('small').textContent=count+' project'+(count===1?'':'s');card.append(overlay);card.onclick=()=>openBrandModal(brand,card);grid.append(card);});}
function openBrandModal(brand,trigger){const modal=document.getElementById('projectModal'), content=modal.querySelector('.modal-content');lastProjectTrigger=trigger;modal.classList.add('is-open','is-brand-modal');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';content.querySelectorAll('.brand-modal-body').forEach(n=>n.remove());const body=document.createElement('div');body.className='brand-modal-body';const title=document.createElement('div');title.className='brand-modal-heading';title.innerHTML='<p>Selected work</p><h3></h3>';title.querySelector('h3').textContent=brand.name;body.append(title);allPortfolioProjects.filter(p=>String(p.brand)===String(brand.id)).forEach(p=>body.append(projectCaseStudy(p)));content.append(body);}
function projectCaseStudy(p){const article=document.createElement('article');article.className='brand-project';const head=document.createElement('div');head.className='brand-project-head';head.innerHTML='<div><span></span><h4></h4></div><button type="button">View media</button>';head.querySelector('span').textContent=p.year||'';head.querySelector('h4').textContent=p.title||'Untitled project';const media=Array.isArray(p.gallery)&&p.gallery.length?p.gallery: [p.video||p.thumbnail].filter(Boolean);const carousel=document.createElement('div');carousel.className='project-carousel';let index=0;function show(){carousel.innerHTML='';if(!media.length){carousel.textContent='No media added.';return;}carousel.append(mediaEl(media[index],p.title,true));const nav=document.createElement('div');nav.className='carousel-nav';nav.innerHTML='<button type="button">←</button><span></span><button type="button">→</button>';nav.querySelector('span').textContent=(index+1)+' / '+media.length;nav.children[0].onclick=()=>{index=(index-1+media.length)%media.length;show()};nav.children[2].onclick=()=>{index=(index+1)%media.length;show()};carousel.append(nav)}show();head.querySelector('button').onclick=()=>article.classList.toggle('is-expanded');const detail=document.createElement('div');detail.className='brand-project-detail';if(p.description){const d=document.createElement('p');d.textContent=p.description;detail.append(d)}if(p.role){const r=document.createElement('p');r.className='brand-project-role';r.textContent='Role: '+p.role;detail.append(r)}article.append(head,carousel,detail);return article;}
function closeProjectModal(){const modal=document.getElementById('projectModal');if(!modal)return;modal.classList.remove('is-open','is-brand-modal');modal.setAttribute('aria-hidden','true');document.body.style.overflow='';if(lastProjectTrigger)lastProjectTrigger.focus();}
Object.assign(window,{loadProjects,renderProjects,closeProjectModal,openBrandModal,renderFilters:()=>{},filterProjects:()=>allPortfolioProjects});
